repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort moin2hugo/
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: black
        entry: poetry run black moin2hugo/
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest tests/
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy-check
        name: mypy-check
        entry: poetry run mypy moin2hugo/
        language: system
        pass_filenames: false
        always_run: true
